# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDesenvolvimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cd', models.CharField(max_length=50, verbose_name=b'Nome do Cart\xc3\xa3o de Desenv')),
                ('desenvolvedor', models.CharField(max_length=50, verbose_name=b'Desenvolvedor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('data_des_ini', models.DateField(blank=True, null=True, verbose_name=b'Data Desenv In\xc3\xadcio')),
                ('data_des_fim', models.DateField(blank=True, null=True, verbose_name=b'Data Desenv Fim')),
                ('obs', models.TextField(blank=True, null=True, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('participacao', models.DecimalField(decimal_places=2, max_digits=3, verbose_name=b'%')),
            ],
            options={
                'verbose_name': 'Cart\xe3o de Desenvovimento',
                'verbose_name_plural': 'Cart\xf5es de Desenvolvimento',
            },
        ),
        migrations.CreateModel(
            name='CPod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cp', models.CharField(max_length=50, verbose_name=b'Nome do Cart\xc3\xa3o')),
                ('cliente', models.CharField(max_length=50, verbose_name=b'Cliente')),
                ('data_ini', models.DateField(verbose_name=b'Data In\xc3\xadcio')),
                ('data_fim', models.DateField(verbose_name=b'Data Final')),
                ('data_des_ini', models.DateField(blank=True, null=True, verbose_name=b'Data Desenv In\xc3\xadcio')),
                ('data_des_fim', models.DateField(blank=True, null=True, verbose_name=b'Data Desenv Final')),
                ('obs', models.TextField(blank=True, null=True, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Status')),
            ],
            options={
                'verbose_name': 'Cart\xe3o de Produ\xe7\xe3o',
                'verbose_name_plural': 'Cat\xf5es de Produ\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Escopo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escopo', models.CharField(max_length=50, verbose_name=b'Escopo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('cpod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.CPod', verbose_name=b'Cart\xc3\xa3o de Produ\xc3\xa7\xc3\xa3o')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDesenvolvimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=50, verbose_name=b'Nome do Item')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('data_ini', models.DateField(blank=True, null=True, verbose_name=b'Data In\xc3\xadcio Real')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name=b'Data Fim Real')),
                ('obs', models.TextField(blank=True, null=True, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('participacao', models.DecimalField(decimal_places=2, max_digits=3, verbose_name=b'%')),
                ('concluido', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name=b'% Conclu\xc3\xaddo')),
                ('cdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.CDesenvolvimento', verbose_name=b'Cart\xc3\xa3o de Desenvolvimento')),
            ],
            options={
                'verbose_name': 'Item de Desenvolvimento',
                'verbose_name_plural': 'Itens de Desenvolvimento',
            },
        ),
        migrations.AddField(
            model_name='cdesenvolvimento',
            name='cpod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.CPod', verbose_name=b'Cart\xc3\xa3o de Produ\xc3\xa7\xc3\xa3o'),
        ),
    ]
