# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpod',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Progresso'),
        ),
    ]
