# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_auto_20170710_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpod',
            name='projeto',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name=b'Projeto'),
            preserve_default=False,
        ),
    ]
