# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_cpod_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=50, verbose_name=b'Tarefa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('data_ini', models.DateField(blank=True, null=True, verbose_name=b'Data In\xc3\xadcio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name=b'Data Final')),
                ('obs', models.TextField(blank=True, null=True, verbose_name=b'Observa\xc3\xa7\xc3\xb5es')),
                ('participacao', models.DecimalField(decimal_places=2, max_digits=3, verbose_name=b'%')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Progresso')),
                ('itdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.ItemDesenvolvimento', verbose_name=b'\xc3\x8dtem de Desenvolvimento')),
            ],
            options={
                'verbose_name': 'Tarefas',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
