# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-28 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_tarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdesenvolvimento',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Progresso'),
        ),
        migrations.AddField(
            model_name='cpod',
            name='participacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name=b'%'),
            preserve_default=False,
        ),
    ]
