# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-29 18:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_auto_20180829_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdesenvolvimento',
            name='participacao',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name=b'Participa\xc3\xa7\xc3\xa3o (%)'),
        ),
        migrations.AlterField(
            model_name='cdesenvolvimento',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name=b'Progresso (%)'),
        ),
        migrations.AlterField(
            model_name='itemdesenvolvimento',
            name='concluido',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name=b'Progresso (%)'),
        ),
        migrations.AlterField(
            model_name='itemdesenvolvimento',
            name='participacao',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name=b'Participa\xc3\xa7\xc3\xa3o (%)'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='participacao',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name=b'Participa\xc3\xa7\xc3\xa3o (%)'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name=b'Progresso (%)'),
        ),
    ]
