# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-21 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_auto_20180829_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdesenvolvimento',
            name='nome_cd',
            field=models.CharField(max_length=50, verbose_name=b'Cart\xc3\xa3o de Desenvolvimento'),
        ),
    ]
